[project]
name = "ocadays"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Pierre Verkest", email = "pierre@verkest.fr" }
]
requires-python = ">=3.14"
dynamic = ["dependencies"]


[tool.uv]
exclude-dependencies = ["PyPDF2"]

[tool.uv.sources]
odoo = {git = "https://github.com/OCA/OCB.git", branch = "19.0"}
#odoo-addon-mis-builder = { git = "https://github.com/OCA/mis-builder.git", rev = "refs/pull/827/head", subdirectory = "mis_builder" }
odoo-addon-mis-builder = { path = ".src/mis-builder/mis_builder", editable = true }

[tool.hatch.build.targets.wheel]
packages = ["src/odoo"]

# Enable the hatch-odoo build hook to package the Odoo addons into odoo/addons.
[tool.hatch.build.hooks.odoo-addons-dirs]
[tool.hatch.metadata.hooks.odoo-addons-dependencies]

[tool.hatch-odoo]
odoo_version_override = "19.0"
# Our addons are in the project root directory.
addons_dirs = ["src/odoo/addons"]

dependencies = [
  "odoo>=19.0",
  "lxml>=5.2.1",
  "lxml_html_clean",
  "Werkzeug==3.0.1",
  "PyPDF==5.4.0",
  "freezegun",
]

[build-system]
requires = ["hatchling", "hatch-odoo"]
build-backend = "hatchling.build"
