[project]
name = "ocadays"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Pierre Verkest", email = "pierre@verkest.fr" }
]
requires-python = ">=3.14"
dynamic = ["dependencies"]


[tool.uv]
exclude-dependencies = ["PyPDF2"]

[tool.uvault]
tag_prefix = "ocadays26"
tag_template = "{tag_prefix}-{sha}"
dev_directory = ".src/"

# VCS Vault Configuration
[[tool.uvault.vcs_vaults]]
provider = "github.com"
owner = "apycod"
default = true

[tool.uvault.sources]
odoo = {git = "https://github.com/OCA/OCB.git", branch = "19.0"}
odoo-addon-mis-builder = { git = "https://github.com/OCA/mis-builder.git", rev = "refs/pull/827/head", subdirectory = "mis_builder" }

[tool.uv.sources]
odoo = {git = "https://github.com/apycod/OCB.git", tag = "ocadays26-b9bfddc88e6114f83bac32e47f179f62b016ceb1"}
odoo-addon-mis-builder = {git = "https://github.com/apycod/mis-builder.git", tag = "ocadays26-07d1ba5cb126e242dabafea5beabf92af0155a1e", subdirectory = "mis_builder"}

[tool.hatch.build.targets.wheel]
packages = ["src/odoo"]

# Enable the hatch-odoo build hook to package the Odoo addons into odoo/addons.
[tool.hatch.build.hooks.odoo-addons-dirs]
[tool.hatch.metadata.hooks.odoo-addons-dependencies]

[tool.hatch-odoo]
odoo_version_override = "19.0"
# Our addons are in the project root directory.
addons_dirs = ["odoo/addons"]

dependencies = [
  "odoo>=19.0",
  "lxml>=5.2.1",
  "lxml_html_clean",
  "Werkzeug==3.0.1",
  "PyPDF==5.4.0",
  "freezegun",
]

[build-system]
requires = ["hatchling", "hatch-odoo"]
build-backend = "hatchling.build"
